### ISSUE TITLE
运行node test.js报错

### ISSUE THREAD

**Issue by shuiRong** [hooklife/dongtu-function#1]
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: Error reinitializing filters!
Failed to inject frame into filter network: No such file or directory
Error while processing the decoded data for stream #0:0
Conversion failed!

    at ChildProcess.<anonymous> (/Users/shuirong/Code/dongtu-function/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

应该不是依赖安装的问题，因为`npm i` `cnpm i` `yarn` 都试过几次。
本机也装过了`ffmpeg`
尝试
`ffmpeg -i templates/wangjingze.mp4 output.gif`
能成功转换成gif

> Google过了，也没找到答案。

搞不明白 **No such file or directory**指的是什么。 tmp/xxxxxxx.gif 和 wangjingze.mp4 都在对应位置。

希望你有答案，感谢。

**PS:**
补充，经排查，错误的语句在 gif.js 的 `on('end'....`

**Comment by hooklife** [comment]
我也不是很清楚这个错误。

你可以在app.js  53行的位置添加一下这个代码

```
.on('start', function(commandLine) {
    console.log('Spawned Ffmpeg with command: ' + commandLine);
  });
```

查看一下程序生成的ffmpeg命令是什么 然后 手动在命令行执行一下观察是否有错误
